### ISSUE TITLE
Improve title

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/requirements-collection-management-systems#5]
@EnnoMeijers You changed the title to _Requirements for CMSs_. However, the first sentence says:

> vendors of software - like collection management systems, and linked data publication platforms

So not _just_ CMSs but also publication and other platforms. 

Some suggestions for an improved title:

- _NDE Compatibility Requirements_
- _NDE Requirements for Software Suppliers_
- _NDE Requirements for Collection Management and Publication Software_

**Comment by EnnoMeijers** [comment]
I propose to stick to requirements for CMS as this is the main focus of these requirements. Some vendor integrate all functionality that is needed to meet these requirements in one platform others offer a combination of services based on multiple platforms. Both approaches should meet all requirements to fulfil the NDE-compliancy. Some stand alone linked data publication platforms offer functionality to support part of the required functionality, these platforms are not the primary focus of this document. I will change the text to reflect this distinction.
